/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TierListIndexRouteImport } from './routes/tier-list/index'

const TierListIndexRoute = TierListIndexRouteImport.update({
  id: '/tier-list/',
  path: '/tier-list/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/tier-list/': typeof TierListIndexRoute
}
export interface FileRoutesByTo {
  '/tier-list': typeof TierListIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/tier-list/': typeof TierListIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/tier-list/'
  fileRoutesByTo: FileRoutesByTo
  to: '/tier-list'
  id: '__root__' | '/tier-list/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TierListIndexRoute: typeof TierListIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tier-list/': {
      id: '/tier-list/'
      path: '/tier-list'
      fullPath: '/tier-list/'
      preLoaderRoute: typeof TierListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  TierListIndexRoute: TierListIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
