/**
 * Custom Stencil output target — generates `components.next-server.ts`.
 *
 * Runs as part of every `stencil build` so the file stays in sync with
 * component definitions automatically, just like `components.ts` and
 * `components.server.ts` are generated by the official react output target.
 *
 * WHY A CUSTOM TARGET (not @stencil/ssr/next):
 *   @stencil/ssr/next is a webpack-only compiler plugin. Next.js 16 uses
 *   Turbopack by default, making it incompatible. Even with webpack it only
 *   works for props whose values are statically known at build time — it
 *   cannot SSR components whose props come from a runtime API call.
 *
 * WHY dangerouslySetInnerHTML (not a <template> React child):
 *   Stencil's SSR renders Declarative Shadow DOM as a <template shadowrootmode>
 *   child element. The browser's HTML parser consumes that <template> before
 *   React hydrates, so React's VDOM (from the RSC payload) no longer matches
 *   the DOM — causing "Hydration failed" errors. Setting the DSD HTML via
 *   dangerouslySetInnerHTML makes React skip child reconciliation entirely for
 *   that element, eliminating the mismatch.
 */

import type { Config, JsonDocsComponent, JsonDocsProp, OutputTargetCustom } from "@stencil/core/internal";
import path from "node:path";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type NextServerOutputTargetOptions = {
	/**
	 * Directory to write `components.next-server.ts` into.
	 * Relative to the Stencil project root. Defaults to `"src/react"`.
	 */
	outDir?: string;

	/**
	 * Import specifier for the Stencil hydrate module.
	 * Defaults to the package name derived from `package.json` + `/hydrate`.
	 */
	hydrateModule?: string;
};

export function nextServerOutputTarget(opts: NextServerOutputTargetOptions = {}): OutputTargetCustom {
	const outDir = opts.outDir ?? "src/react";

	return {
		type: "custom",
		name: "next-server-components",

		// oxlint-disable-next-line max-params -- Stencil OutputTargetCustom.generator requires exactly these 4 parameters
		async generator(config: Config, compilerCtx, _buildCtx, docs) {
			// Resolve the hydrate module name from package.json when not provided.
			const hydrateModule =
				opts.hydrateModule ??
				(config.sys && config.packageJsonFilePath
					? `${JSON.parse(config.sys.readFileSync(config.packageJsonFilePath, "utf8") ?? "{}").name}/hydrate`
					: "@rift/ui/hydrate");

			const components = docs.components.filter(c => !c.internal);

			if (components.length === 0) {
				return;
			}

			const content = generateFile(components, hydrateModule);

			// config.rootDir is always set by the time generator runs
			// oxlint-disable-next-line typescript/no-non-null-assertion -- rootDir is guaranteed to be set when the generator runs
			const outPath = path.join(config.rootDir!, outDir, "components.next-server.ts");
			await compilerCtx.fs.writeFile(outPath, content);
		},
	};
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function toPascalCase(tag: string): string {
	return tag
		.split("-")
		.map(s => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/** Returns the default value expression to embed in the generated code. */
function defaultExpr(prop: JsonDocsProp): string {
	if (prop.default !== undefined) {
		return prop.default;
	}
	// Infer a safe fallback when the source has no initialiser (e.g. required props).
	if (prop.type.includes("number")) {
		return "0";
	}
	if (prop.type.includes("boolean")) {
		return "false";
	}
	return '""';
}

function generateComponentExport(component: JsonDocsComponent): string {
	const name = toPascalCase(component.tag);
	const props = component.props.filter(p => !p.internal);

	// Props interface lines — all optional so callers can omit any prop.
	const propLines = props.map(p => `\t${p.name}?: ${p.type};`).join("\n");

	// renderStencilElement attr-map entries.
	const attrLines = props
		.map(p => {
			const attr = p.attr ?? p.name;
			const def = defaultExpr(p);
			// Quoted key when the HTML attribute name differs from the prop name
			// (e.g. splashArtUrl → "splash-art-url").
			const key = attr === p.name ? attr : `"${attr}"`;
			return `\t\t${key}: props.${p.name} ?? ${def},`;
		})
		.join("\n");

	return `export type ${name}Events = NonNullable<unknown>;

export async function ${name}(props: {
${propLines}
}): Promise<React.ReactElement> {
\treturn renderStencilElement("${component.tag}", {
${attrLines}
\t});
}`;
}

function generateFile(components: JsonDocsComponent[], hydrateModule: string): string {
	const componentExports = components.map(c => generateComponentExport(c)).join("\n\n");

	return `/**
 * Next.js App Router RSC entry for Stencil React wrappers.
 *
 * AUTO-GENERATED by the nextServerOutputTarget custom output target.
 * Re-generated on every \`stencil build\` — do not edit manually.
 *
 * No "use client" directive — Next.js resolves this file via the "react-server"
 * export condition so it runs as a true React Server Component.
 */

import type { HydrateResults } from "${hydrateModule}";
import React from "react";

let _hydrate: typeof import("${hydrateModule}") | null = null;

async function getHydrate() {
\tif (!_hydrate) {
\t\t_hydrate = await import("${hydrateModule}");
\t}
\treturn _hydrate;
}

type AttrValue = string | number | boolean | null | undefined;

async function renderStencilElement(
\ttagName: string,
\tattrs: Record<string, AttrValue>,
): Promise<React.ReactElement> {
\tconst hydrate = await getHydrate();

\tconst attrStr = Object.entries(attrs)
\t\t.filter(([, v]) => v != null && v !== false)
\t\t.map(([k, v]) => \` \${k}="\${String(v).replace(/&/g, "&amp;").replace(/"/g, "&quot;")}"\`)
\t\t.join("");

\tconst result: HydrateResults = await hydrate.renderToString(
\t\t\`<\${tagName}\${attrStr}></\${tagName}>\`,
\t\t{ fullDocument: false, serializeShadowRoot: "declarative-shadow-dom", prettyHtml: false },
\t);

\tconst html = result.html ?? "";

\t// Strip the outer wrapper — keep only the DSD inner content.
\tconst innerHtml = html
\t\t.replace(new RegExp(\`^\\\\s*<\${tagName}[^>]*>\`, "i"), "")
\t\t.replace(new RegExp(\`</\${tagName}>\\\\s*$\`, "i"), "")
\t\t.trim();

\tconst styleElements = (result.styles ?? [])
\t\t.filter((s) => s.content)
\t\t.map((s, i) =>
\t\t\tReact.createElement("style", {
\t\t\t\tkey: s.id ?? i,
\t\t\t\tid: s.id,
\t\t\t\tprecedence: "stencil",
\t\t\t\tsuppressHydrationWarning: true,
\t\t\t\tdangerouslySetInnerHTML: { __html: s.content! },
\t\t\t}),
\t\t);

\tconst el = React.createElement(tagName, {
\t\t...(attrs as React.HTMLAttributes<HTMLElement>),
\t\tsuppressHydrationWarning: true,
\t\tdangerouslySetInnerHTML: { __html: innerHtml },
\t} as React.HTMLAttributes<HTMLElement>);

\treturn styleElements.length > 0
\t\t? React.createElement(React.Fragment, null, ...styleElements, el)
\t\t: el;
}

${componentExports}
`;
}
