/**
 * Custom Stencil output target — generates `components.next-server.ts` and
 * `components.next-client.tsx`.
 *
 * Runs as part of every `stencil build` so the files stay in sync with
 * component definitions automatically, just like `components.ts` and
 * `components.server.ts` are generated by the official react output target.
 *
 * WHY A CUSTOM TARGET (not @stencil/ssr/next):
 *   @stencil/ssr/next is a webpack-only compiler plugin. Next.js 16 uses
 *   Turbopack by default, making it incompatible. Even with webpack it only
 *   works for props whose values are statically known at build time — it
 *   cannot SSR components whose props come from a runtime API call.
 *
 * WHY TWO FILES (server + client):
 *   The RSC entry (components.next-server.ts) calls renderToString() and emits
 *   Declarative Shadow DOM via dangerouslySetInnerHTML. The browser's HTML
 *   parser processes <template shadowrootmode> on initial load, but React's
 *   innerHTML (used during client-side navigation) does not — causing blank
 *   cards on navigation. The client entry (components.next-client.tsx) fixes
 *   this by:
 *     1. Calling defineCustomElement() so Stencil's custom element class is
 *        registered in the browser (it would otherwise never be registered,
 *        since the react-server export condition bypasses components.ts).
 *     2. Calling setHTMLUnsafe() when no shadow root is found after mount,
 *        which properly parses <template shadowrootmode> on client navigation.
 */

import type { Config, JsonDocsComponent, JsonDocsProp, OutputTargetCustom } from "@stencil/core/internal";
import path from "node:path";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export type NextServerOutputTargetOptions = {
	/**
	 * Directory to write the generated files into.
	 * Relative to the Stencil project root. Defaults to `"src/react"`.
	 */
	outDir?: string;

	/**
	 * Import specifier for the Stencil hydrate module.
	 * Defaults to the package name derived from `package.json` + `/hydrate`.
	 */
	hydrateModule?: string;

	/**
	 * Package name used to build per-component `defineCustomElement` import
	 * paths (e.g. `"@scope/my-stencil-lib"`). Defaults to `hydrateModule`
	 * with its trailing path segment (conventionally `/hydrate`) stripped.
	 */
	packageName?: string;
};

export function nextServerOutputTarget(opts: NextServerOutputTargetOptions = {}): OutputTargetCustom {
	const outDir = opts.outDir ?? "src/react";

	return {
		type: "custom",
		name: "next-server-components",

		// oxlint-disable-next-line max-params -- Stencil OutputTargetCustom.generator requires exactly these 4 parameters
		async generator(config: Config, compilerCtx, _buildCtx, docs) {
			// Resolve the hydrate module name from package.json when not provided.
			const hydrateModule =
				opts.hydrateModule ??
				(config.sys && config.packageJsonFilePath
					? `${JSON.parse(config.sys.readFileSync(config.packageJsonFilePath, "utf8") ?? "{}").name}/hydrate`
					: (() => {
							throw new Error(
								"[next-server-components] Could not resolve hydrateModule automatically. " +
									"Please pass the hydrateModule option explicitly, e.g. " +
									'nextServerOutputTarget({ hydrateModule: "my-package/hydrate" })',
							);
						})());

			// Derive package name: strip the trailing path segment from hydrateModule
			// (convention: hydrateModule = packageName + "/hydrate").
			// e.g. "@rift/ui/hydrate" → "@rift/ui", "my-lib/hydrate" → "my-lib"
			const packageName = opts.packageName ?? hydrateModule.split("/").slice(0, -1).join("/");

			const components = docs.components.filter(c => !c.internal);

			if (components.length === 0) {
				return;
			}

			// config.rootDir is always set by the time generator runs
			// oxlint-disable-next-line typescript/no-non-null-assertion -- rootDir is guaranteed to be set when the generator runs
			const rootDir = config.rootDir!;

			const serverContent = generateServerFile(components, hydrateModule);
			await compilerCtx.fs.writeFile(path.join(rootDir, outDir, "components.next-server.ts"), serverContent);

			const clientContent = generateClientFile(components, packageName);
			await compilerCtx.fs.writeFile(path.join(rootDir, outDir, "components.next-client.tsx"), clientContent);
		},
	};
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

function toPascalCase(tag: string): string {
	return tag
		.split("-")
		.map(s => s.charAt(0).toUpperCase() + s.slice(1))
		.join("");
}

/** Returns the default value expression to embed in the generated code. */
function defaultExpr(prop: JsonDocsProp): string {
	if (prop.default !== undefined) {
		return prop.default;
	}
	// Infer a safe fallback when the source has no initialiser (e.g. required props).
	if (prop.type.includes("number")) {
		return "0";
	}
	if (prop.type.includes("boolean")) {
		return "false";
	}
	return '""';
}

function generateComponentExport(component: JsonDocsComponent): string {
	const name = toPascalCase(component.tag);
	const props = component.props.filter(p => !p.internal);

	// Props interface lines — all optional so callers can omit any prop.
	// children is always included so callers can pass slotted content.
	const propLines = [...props.map(p => `\t${p.name}?: ${p.type};`), "\tchildren?: React.ReactNode;"].join("\n");

	// Attr-map entries passed to both renderStencilElement (SSR) and the Host
	// client component (for React prop reconciliation on re-renders).
	const attrLines = props
		.map(p => {
			const attr = p.attr ?? p.name;
			const def = defaultExpr(p);
			// Quoted key when the HTML attribute name differs from the prop name
			// (e.g. splashArtUrl → "splash-art-url").
			const key = attr === p.name ? attr : `"${attr}"`;
			return `\t\t${key}: props.${p.name} ?? ${def},`;
		})
		.join("\n");

	return `export type ${name}Events = NonNullable<unknown>;

export async function ${name}(props: {
${propLines}
}): Promise<React.ReactElement> {
\tconst attrs: Record<string, AttrValue> = {
${attrLines}
\t};
	const { shadowContent, styleElements, stencilHostAttrs } = await renderStencilElement("${component.tag}", attrs);
	const host = React.createElement(${name}Host, { shadowContent, attrs: { ...attrs, ...stencilHostAttrs } }, props.children);
\treturn styleElements.length > 0
\t\t? React.createElement(React.Fragment, null, ...styleElements, host)
\t\t: host;
}`;
}

function generateServerFile(components: JsonDocsComponent[], hydrateModule: string): string {
	const hostImports = components.map(c => `${toPascalCase(c.tag)}Host`).join(", ");
	const componentExports = components.map(c => generateComponentExport(c)).join("\n\n");

	return `/**
 * Next.js App Router RSC entry for Stencil React wrappers.
 *
 * AUTO-GENERATED by the nextServerOutputTarget custom output target.
 * Re-generated on every \`stencil build\` — do not edit manually.
 *
 * No "use client" directive — Next.js resolves this file via the "react-server"
 * export condition so it runs as a true React Server Component.
 */

import type { HydrateResults } from "${hydrateModule}";
import React from "react";
import { ${hostImports} } from "./components.next-client";

let _hydrate: typeof import("${hydrateModule}") | null = null;

async function getHydrate() {
\tif (!_hydrate) {
\t\t_hydrate = await import("${hydrateModule}");
\t}
\treturn _hydrate;
}

type AttrValue = string | number | boolean | null | undefined;

async function renderStencilElement(
\ttagName: string,
\tattrs: Record<string, AttrValue>,
): Promise<{ shadowContent: string; styleElements: React.ReactElement[]; stencilHostAttrs: Record<string, string> }> {
\tconst hydrate = await getHydrate();

\tconst attrStr = Object.entries(attrs)
\t\t.filter(([, v]) => v != null && v !== false)
\t\t.map(([k, v]) => \` \${k}="\${String(v).replace(/&/g, "&amp;").replace(/"/g, "&quot;")}"\`)
\t\t.join("");

\tconst result: HydrateResults = await hydrate.renderToString(
\t\t\`<\${tagName}\${attrStr}></\${tagName}>\`,
\t\t{ fullDocument: false, serializeShadowRoot: "declarative-shadow-dom", prettyHtml: false },
\t);

\tconst html = result.html ?? "";

\t// Extract Stencil's s-id from the outer tag. renderToString adds s-id to the
\t// host element so the client runtime can identify it as SSR'd and perform
\t// hydration patching (reusing DSD shadow DOM) instead of a fresh render
\t// (which would append to the existing shadow DOM and duplicate content).
\tconst outerTagMatch = html.match(new RegExp(\`<\${tagName}([^>]*)>\`, "i"));
\tconst outerTagAttrs = outerTagMatch?.[1] ?? "";
\tconst sIdMatch = outerTagAttrs.match(/\\bs-id="([^"]+)"/);
\tconst stencilHostAttrs: Record<string, string> = sIdMatch ? { "s-id": sIdMatch[1] } : {};

\t// Strip the outer wrapper — keep only the DSD inner content.
\tconst innerHtml = html
\t\t.replace(new RegExp(\`^\\\\s*<\${tagName}[^>]*>\`, "i"), "")
\t\t.replace(new RegExp(\`</\${tagName}>\\\\s*$\`, "i"), "")
		.trim();
	// Extract the content inside <template shadowrootmode="open"> so it can be
	// rendered as a React <template> element (for SSR) and used directly with
	// attachShadow().innerHTML (for client navigation) — keeping light DOM
	// children (slots) React-managed without interference.
	//
	// Stencil appends a hydration marker comment (e.g. <!--r.1-->) AFTER the
	// closing </template> tag. Strip all trailing Stencil comments before
	// matching, otherwise the $ anchor never matches and shadowContent keeps
	// the full <template> tag — causing a double-nested DSD in the React output.
	const innerHtmlClean = innerHtml.replace(/<!--[^>]*-->\\s*$/g, "").trim();
	const templateMatch = innerHtmlClean.match(/^<template[^>]*>([\\s\\S]*)<\\/template>$/i);
	const shadowContent = templateMatch?.[1] ?? innerHtmlClean;
	const styleElements = (result.styles ?? [])
\t\t.filter((s) => s.content)
\t\t.map((s, i) =>
\t\t\tReact.createElement("style", {
\t\t\t\tkey: s.id ?? i,
\t\t\t\tid: s.id,
\t\t\t\tprecedence: "stencil",
\t\t\t\tsuppressHydrationWarning: true,
\t\t\t\tdangerouslySetInnerHTML: { __html: s.content! },
\t\t\t}),
\t\t);

	return { shadowContent, styleElements, stencilHostAttrs };
}

${componentExports}
`;
}

function generateClientFile(components: JsonDocsComponent[], packageName: string): string {
	const importLines = components
		.map(c => {
			const name = toPascalCase(c.tag);
			return `import { defineCustomElement as define${name} } from "${packageName}/dist/components/${c.tag}.js";`;
		})
		.join("\n");

	const componentExports = components
		.map(c => {
			const name = toPascalCase(c.tag);
			return `let _defined${name} = false;

export function ${name}Host({ shadowContent, attrs, children }: StencilHostProps) {
\tconst ref = React.useRef<HTMLElement>(null);
\tReact.useLayoutEffect(() => {
\t\tconst el = ref.current;
\t\tif (!el) return;
\t\t// Pre-attach the shadow root BEFORE registering the custom element.
\t\t// When defineCustomElement() triggers the upgrade, Stencil's connectedCallback
\t\t// checks el.shadowRoot before calling attachShadow. By pre-attaching here we
\t\t// ensure Stencil never attempts attachShadow on an element that already has a
\t\t// shadow root (from DSD on initial SSR load or from our own call on navigation).
\t\tif (!el.shadowRoot) {
\t\t\t// Client-side navigation: no DSD shadow root exists yet.
\t\t\tconst shadow = el.attachShadow({ mode: "open" });
\t\t\tshadow.innerHTML = shadowContent;
\t\t}
\t\tif (!_defined${name}) {
\t\t\tdefine${name}();
\t\t\t_defined${name} = true;
\t\t}
\t}, [shadowContent]);
\t// During SSR, render the DSD as a <template shadowrootmode> child alongside
\t// light DOM children. The browser HTML parser consumes the <template> and
\t// creates the shadow root; after parsing it is no longer in the DOM, leaving
\t// only the slotted children — which matches the client render path below,
\t// making hydration mismatch-free.
\tif (typeof window === "undefined") {
\t\treturn React.createElement(
\t\t\t"${c.tag}",
\t\t\t{ ...(attrs as React.HTMLAttributes<HTMLElement>), suppressHydrationWarning: true } as React.HTMLAttributes<HTMLElement>,
\t\t\tReact.createElement("template", { shadowrootmode: "open", suppressHydrationWarning: true, dangerouslySetInnerHTML: { __html: shadowContent } } as unknown as React.HTMLAttributes<HTMLElement>),
\t\t\tchildren,
\t\t);
\t}
\treturn React.createElement("${c.tag}", {
\t\tref,
\t\t...(attrs as React.HTMLAttributes<HTMLElement>),
\t\tsuppressHydrationWarning: true,
\t} as React.HTMLAttributes<HTMLElement>, children);
}`;
		})
		.join("\n\n");

	return `'use client';
/**
 * AUTO-GENERATED by the nextServerOutputTarget custom output target.
 * Re-generated on every \`stencil build\` — do not edit manually.
 *
 * Client-side wrappers for Stencil web components. Each wrapper:
 *   1. Registers the custom element (defineCustomElement) on first render so
 *      Stencil's connectedCallback fires on client-side navigation. Without
 *      this the element is unknown — the react-server export condition bypasses
 *      components.ts which is the only file that would call it.
 *   2. Restores the shadow root via attachShadow().innerHTML on client-side
 *      navigation, without clobbering React-managed light DOM children (slots).
 *   3. Renders the DSD as a <template shadowrootmode> React child during SSR.
 *      The browser's HTML parser consumes the template and creates the shadow
 *      root, leaving only light DOM children for React to hydrate against.
 */
import React from "react";
${importLines}

type AttrValue = string | number | boolean | null | undefined;
type StencilHostProps = {
\tshadowContent: string;
\tattrs: Record<string, AttrValue>;
\tchildren?: React.ReactNode;
};

${componentExports}
`;
}
