/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChampionsIndexRouteImport } from './routes/champions/index'
import { Route as ChampionsIdRouteImport } from './routes/champions/$id'

const ChampionsIndexRoute = ChampionsIndexRouteImport.update({
  id: '/champions/',
  path: '/champions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsIdRoute = ChampionsIdRouteImport.update({
  id: '/champions/$id',
  path: '/champions/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/champions/$id': typeof ChampionsIdRoute
  '/champions/': typeof ChampionsIndexRoute
}
export interface FileRoutesByTo {
  '/champions/$id': typeof ChampionsIdRoute
  '/champions': typeof ChampionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/champions/$id': typeof ChampionsIdRoute
  '/champions/': typeof ChampionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/champions/$id' | '/champions/'
  fileRoutesByTo: FileRoutesByTo
  to: '/champions/$id' | '/champions'
  id: '__root__' | '/champions/$id' | '/champions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ChampionsIdRoute: typeof ChampionsIdRoute
  ChampionsIndexRoute: typeof ChampionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/champions/': {
      id: '/champions/'
      path: '/champions'
      fullPath: '/champions/'
      preLoaderRoute: typeof ChampionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/$id': {
      id: '/champions/$id'
      path: '/champions/$id'
      fullPath: '/champions/$id'
      preLoaderRoute: typeof ChampionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ChampionsIdRoute: ChampionsIdRoute,
  ChampionsIndexRoute: ChampionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
