/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlayerIndexRouteImport } from './routes/player/index'

const PlayerIndexRoute = PlayerIndexRouteImport.update({
  id: '/player/',
  path: '/player/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/player/': typeof PlayerIndexRoute
}
export interface FileRoutesByTo {
  '/player': typeof PlayerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/player/': typeof PlayerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/player/'
  fileRoutesByTo: FileRoutesByTo
  to: '/player'
  id: '__root__' | '/player/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PlayerIndexRoute: typeof PlayerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/player/': {
      id: '/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof PlayerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  PlayerIndexRoute: PlayerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
